const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
function setup(edit=true){
 const nodes={},events={},timers=new Map();let seq=0,token='test-token',post=async()=>({ok:true,item:{noteKey:'key',note:'saved',noteVersion:1}});
 function node(id){if(!nodes[id]){const classes=new Set(id==='rtNoteModal'?['hidden']:[]);nodes[id]={id,textContent:'',innerHTML:'',value:'',listeners:{},dataset:{},style:{setProperty(){}},classList:{add:x=>classes.add(x),remove:x=>classes.delete(x),contains:x=>classes.has(x),toggle(x,yes){if(yes)classes.add(x);else classes.delete(x);}},setAttribute(k,v){this[k]=v;},focus(options){this.focusOptions=options;},scrollIntoView(){},getBoundingClientRect:()=>({top:100}),addEventListener(type,fn){this.listeners[type]=fn;},querySelectorAll:()=>[]};}return nodes[id];}
 const card={dataset:{priorityId:'RTS_2'},focus(options){this.focusOptions=options;},closest(selector){return selector.includes('button')?null:this;}};
 const item={priorityId:'RTS_2',noteKey:'key',noteVersion:0,rtNo:'123456',plantCode:'7201',capacity:'12X40S',demandSource:'MRP',status:'緊急',note:'<img src=x onerror=alert(1)>\n備註',readOnly:true,source:'RT_SCHEDULE',demandQty:2,unit:'框'};
 const context=vm.createContext({window:{DS_RT_SCHEDULE_MODEL:require('../rt-schedule-model.js'),addEventListener(){}},document:{addEventListener:(t,f)=>events[t]=f,querySelector:()=>null},$:node,state:{priorities:[item],filter:'7201'},permission:()=>edit,renderHomeLoadState:()=>false,renderPriorities(){},getToken:()=>token,portalPost:(...args)=>post(...args),crypto:{randomUUID:()=>String(++seq).padStart(20,'0')},AbortController,getComputedStyle:()=>({top:'100px'}),escapeHtml:s=>String(s??'').replace(/</g,'&lt;').replace(/>/g,'&gt;'),openPriorityModal(){},setTimeout:f=>{timers.set(++seq,f);return seq;},clearTimeout:n=>timers.delete(n)});
 const buttons=['ALL','7201','7209','7973','7A39','Other'].map(status=>({dataset:{status},scrollIntoView(){},click(){context.state.filter=status;context.renderPriorities();}}));node('statusFilters').querySelectorAll=()=>buttons;
 vm.runInContext(fs.readFileSync(require('node:path').join(__dirname,'../rt-schedule-board.js'),'utf8'),context);
 return{node,item,card,events,context,post:fn=>post=fn,token:v=>token=v,submit:()=>node('rtNoteForm').listeners.submit({preventDefault(){}}),open(){node('priorityList').listeners.keydown({target:card,key:'Enter',preventDefault(){}});},fire(type,extra={}){node('priorityList').listeners[type]({target:card,button:0,pointerType:'touch',pointerId:1,clientX:120,clientY:20,...extra});},tick(){for(const f of [...timers.values()])f();timers.clear();}};
}
test('stationary long press opens DS notes as plain text; closing restores focus without scroll',()=>{const s=setup(false);s.fire('pointerdown');s.tick();assert.equal(s.node('rtNoteModal').classList.contains('hidden'),false);assert.equal(s.node('rtNoteText').textContent,s.item.note);assert.equal(s.node('rtNoteText').innerHTML,'');assert.equal(s.node('rtNoteForm').classList.contains('hidden'),true);s.node('closeRtNoteBtn').listeners.click();assert.equal(s.node('rtNoteModal').classList.contains('hidden'),true);assert.equal(s.card.focusOptions.preventScroll,true);});
test('scroll, pointer cancellation, short tap and vertical movement never open notes or switch plant',()=>{for(const cancel of ['pointerup','pointercancel','pointermove','scroll']){const s=setup();s.fire('pointerdown');cancel==='scroll'?s.events.scroll():s.fire(cancel,{clientY:100});s.tick();assert.equal(s.node('rtNoteModal').classList.contains('hidden'),true,cancel);assert.equal(s.context.state.filter,'7201');}});
test('left and right touch swipe switch plants; mouse drag, controls, vertical scroll and boundaries do not',()=>{
 const s=setup();s.fire('pointerdown');s.fire('pointermove',{clientX:20});s.fire('pointerup',{clientX:20});assert.equal(s.context.state.filter,'7209');s.fire('pointerdown');s.fire('pointerup',{clientX:220});assert.equal(s.context.state.filter,'7201');
 for(const extra of [{pointerType:'mouse'},{target:{closest:()=>({})}}]){s.fire('pointerdown',extra);s.fire('pointerup',{clientX:20,...extra});assert.equal(s.context.state.filter,'7201');}
 s.fire('pointerdown');s.fire('pointermove',{clientY:100});s.fire('pointerup',{clientX:20,clientY:110});assert.equal(s.context.state.filter,'7201');s.context.state.filter='Other';s.fire('pointerdown');s.fire('pointerup',{clientX:20});assert.equal(s.context.state.filter,'Other');
});
test('keyboard opens notes; imported cards show only requested quantity and no process/loaded fields',()=>{const s=setup();s.open();assert.equal(s.node('rtNoteForm').classList.contains('hidden'),false);s.node('rtNoteModal').listeners.keydown({key:'Escape',preventDefault(){}});assert.equal(s.node('rtNoteModal').classList.contains('hidden'),true);const html=s.node('priorityList').innerHTML;assert.doesNotMatch(html,/data-edit-id|製程中|裝框/);assert.match(html,/未完成量：2框/);});
test('save updates matching key; uncertain retry retains request id and blocks duplicate submit',async()=>{
 const s=setup();s.open();s.node('rtNoteInput').value='saved';const sent=[];let release;s.post(async(api,data)=>{sent.push({...data});if(sent.length===1)await new Promise(r=>release=r);return {ok:true,item:{noteKey:'key',note:'saved',noteVersion:1}};});
 const first=s.submit();await s.submit();assert.equal(sent.length,1);release();await first;assert.equal(s.item.note,'saved');assert.equal(s.item.noteVersion,1);assert.equal(s.node('rtNoteInput').readOnly,false);
 s.node('rtNoteInput').value='next';s.post(async(api,data)=>{sent.push({...data});throw Error('network');});await s.submit();await s.submit();assert.equal(sent[1].request_id,sent[2].request_id);assert.equal(s.node('rtNoteInput').readOnly,true);
});
test('conflict preserves draft and requires explicitly loading current shared note',async()=>{const s=setup();s.open();s.node('rtNoteInput').value='mine';s.post(async()=>{const e=new Error('conflict');e.code='RT_NOTE_CONFLICT';e.item={noteKey:'key',note:'theirs',noteVersion:2};throw e;});await s.submit();assert.equal(s.node('rtNoteInput').value,'mine');assert.equal(s.node('saveRtNoteBtn').disabled,true);assert.equal(s.item.note,'theirs');s.node('reloadRtNoteBtn').listeners.click();assert.equal(s.node('rtNoteInput').value,'theirs');assert.equal(s.node('saveRtNoteBtn').disabled,false);});
test('logout clears draft, aborts request and ignores its late response',async()=>{const s=setup();s.open();let release,signal;s.post(async(api,data,control)=>{signal=control.signal;return new Promise(r=>release=r);});const saving=s.submit();s.context.window.__DS_RT_SCHEDULE_BOARD.reset();s.token('different');release({ok:true,item:{noteKey:'key',note:'late',noteVersion:1}});await saving;assert.equal(signal.aborted,true);assert.notEqual(s.item.note,'late');assert.equal(s.node('rtNoteInput').value,'');assert.equal(s.node('rtNoteModal').classList.contains('hidden'),true);});
