const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
function setup(){
 const nodes={},events={},timers=new Map();let seq=0;
 function node(id){if(!nodes[id]){const classes=new Set(id==='rtNoteModal'?['hidden']:[]);nodes[id]={id,textContent:'',innerHTML:'',listeners:{},classList:{add:x=>classes.add(x),remove:x=>classes.delete(x),contains:x=>classes.has(x)},setAttribute(k,v){this[k]=v;},focus(options){this.focusOptions=options;},addEventListener(type,fn){this.listeners[type]=fn;},querySelectorAll:()=>[]};}return nodes[id];}
 const card={dataset:{priorityId:'RTS_2'},focus(options){this.focusOptions=options;},closest(selector){return selector==='button'?null:this;}};
 const item={priorityId:'RTS_2',rtNo:'123456',plantCode:'7201',capacity:'12X40S',status:'緊急',note:'<img src=x onerror=alert(1)>\n備註',readOnly:true,source:'RT_SCHEDULE',demandQty:2,unit:'框'};
 const context=vm.createContext({window:{DS_RT_SCHEDULE_MODEL:require('../rt-schedule-model.js')},document:{addEventListener:(t,f)=>events[t]=f},$:node,state:{priorities:[item],filter:'ALL'},permission:()=>true,renderHomeLoadState:()=>false,renderPriorities(){},escapeHtml:s=>String(s??'').replace(/</g,'&lt;').replace(/>/g,'&gt;'),openPriorityModal(){},setTimeout:f=>{timers.set(++seq,f);return seq;},clearTimeout:n=>timers.delete(n)});
 vm.runInContext(fs.readFileSync(require('node:path').join(__dirname,'../rt-schedule-board.js'),'utf8'),context);
 return{node,item,card,events,context,fire(type,extra={}){node('priorityList').listeners[type]({target:card,button:0,clientX:20,clientY:20,...extra});},tick(){for(const f of [...timers.values()])f();timers.clear();}};
}
test('stationary long press opens notes as plain text; closing restores focus without scroll',()=>{const s=setup();s.fire('pointerdown');s.tick();assert.equal(s.node('rtNoteModal').classList.contains('hidden'),false);assert.equal(s.node('rtNoteText').textContent,s.item.note);assert.equal(s.node('rtNoteText').innerHTML,'');s.node('closeRtNoteBtn').listeners.click();assert.equal(s.node('rtNoteModal').classList.contains('hidden'),true);assert.equal(s.card.focusOptions.preventScroll,true);});
test('scroll, pointer cancellation, short tap and movement never trigger long press',()=>{for(const cancel of ['pointerup','pointercancel','pointermove','scroll']){const s=setup();s.fire('pointerdown');cancel==='scroll'?s.events.scroll():s.fire(cancel,{clientY:60});s.tick();assert.equal(s.node('rtNoteModal').classList.contains('hidden'),true,cancel);}});
test('keyboard can open and escape notes, and imported rows have no editing action',()=>{const s=setup();let prevented=0;s.fire('keydown',{key:'Enter',preventDefault:()=>prevented++});assert.equal(prevented,1);assert.equal(s.node('rtNoteModal').classList.contains('hidden'),false);s.node('rtNoteModal').listeners.keydown({key:'Escape',preventDefault(){}});assert.equal(s.node('rtNoteModal').classList.contains('hidden'),true);assert.doesNotMatch(s.node('priorityList').innerHTML,/data-edit-id/);assert.match(s.node('priorityList').innerHTML,/未完成量/);});
